Repository techniche-mcspb2311/techniche, pull requests merged in 2024-02, with the labels that each got.

#23 Nodemailer
  .env.local.template
  package-lock.json
  package.json
  src/app/api/testemail/route.js
  src/email.js
Labels: essential, back-end

#29 updated docs
  README.md
Labels: documentation, back-end

#38 NavBar changes
  package-lock.json
  package.json
  src/app/components/NavBar.jsx
  src/app/landing/components/02-Product.jsx
  src/app/landing/components/03-Trusted.jsx
  src/app/landing/components/04-Features.jsx
  src/app/landing/components/05-Testimonials.jsx
  src/app/landing/components/06-Highlights.jsx
  src/app/landing/components/08-FAQ.jsx
  src/app/landing/components/09-SiteInfoFooter.jsx
  src/app/landing/components/10-LegalFooter.jsx
  src/app/landing/components/11-DarkMode.jsx
  src/app/landing/getLPTheme.js
Labels: front-end
